OTP attribution enhancement
TickyWill/BiblioMeter pull request #22
Opened 2024-12-06 20:33 UTC by TickyWill

This branch integrates the changes proppsed on branch  files_format_refact. 
The specific changes of this branch allows OTP attribution at laboratory level. This required to update the add_otp function but also de set_saved_otps function that use the saved history of OTP attribution at previous treatments.
Also thee functions have been distributed over new python modules to clean the code.
Thanks for review before merge into v6.0.0 branch.

2024-12-13 09:40 UTC, BaptisteRefalo commented
Bien penser à utiliser Pylint avant le merge, il y a des trucs à revoir (trailing-whitespace entre autres 😉)

2024-12-13 09:58 UTC, TickyWill commented
Tout à fait !!! je mets ça au programme. Je suis en train de rédiger la procédure qui rappellera aussi le passage par pylint ! 👍Envoyé de mon iPhoneLe 13 déc. 2024 à 10:40, Baptiste Refalo ***@***.***> a écrit :﻿
Bien penser à utiliser Pylint avant le merge, il y a des trucs à revoir (trailing-whitespace entre autres 😉)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

2024-12-13 16:03 UTC, BaptisteRefalo requested changes
Review done 😊 (some elements to be improved)
Another thing: every script must end with an empty line

2024-12-13 17:51 UTC, TickyWill commented on bmfuncts/add_ifs.py
> +                pass
I'll remove it. It was for seek of clarity but I do agree it is not useful.

2024-12-13 17:55 UTC, TickyWill commented on bmfuncts/build_otps_info.py
> +def set_lab_otps(institute, org_tup, bibliometer_path):
This was the case for number of other functions. I have resolved this by the introduction of intermediate functions but several functions still need to be splitted. I"ll keep this point for the next release. Thanks

2024-12-13 17:57 UTC, TickyWill commented on bmfuncts/format_files.py
> +    homonyms_alias = pg.DF_TITLES_LIST[1]
Oui pylint l'a relevé et je l'ai supprimée.

2024-12-13 18:40 UTC, TickyWill commented on bmfuncts/format_files.py
> +def format_wb_sheet(sheet_name, df, df_title, wb, first,
Docstrings have been updated . Thanks

2024-12-13 18:41 UTC, TickyWill commented on bmfuncts/format_files.py
> +def format_page(df, df_title, attr_keys_list=None, wb=None,
Docstrings have been updated. Thanks

2024-12-14 06:04 UTC, TickyWill commented on bmfuncts/impact_factors_analysis.py
> +def _build_basic_kpi_dict(dept_analysis_df, dept_books_kpi_dict, cols_tup):
Docstring corrected. Thanks.

2024-12-14 06:05 UTC, TickyWill commented on bmfuncts/impact_factors_analysis.py
> +def _build_analysis_if_data(institute, org_tup, analysis_df,
Docstring corrected. Thanks.

2024-12-14 06:05 UTC, TickyWill commented on bmfuncts/format_files.py
> +def set_df_attributes(df_title, df_cols_list, keys_list):
Docstring filled. Thanks.

2024-12-14 06:05 UTC, TickyWill commented on bmfuncts/format_files.py
> +    init_attr_nb = len(init_attr_list)
Oui pylint l'a relevé et je l'ai supprimée.

2024-12-14 06:06 UTC, TickyWill commented on bmfuncts/format_files.py
> +# ToDo: Update of docstrings
Yes ! Now done. Thanks

2024-12-14 06:14 UTC, TickyWill commented on bmfuncts/rename_cols.py
> +def set_col_attr(institute, org_tup, columns_list):
Done. Thanks

2024-12-14 06:16 UTC, TickyWill commented on bmfuncts/rename_cols.py
> +            final_attr_dict[col] = [15, "center"]
Relevé aussi par pylint. Corrigé. Thanks

2024-12-14 06:18 UTC, TickyWill commented on bmfuncts/use_otps.py
> +    if auth_idx in otp_to_set_dpt_df.index:
Pointed out by pylint too. Corrected. Thanks

2024-12-14 06:21 UTC, TickyWill commented on bmfuncts/use_otps.py
> +    else:
It is just for applying some indicated good practices advising for not leaving "if" statement without complementary case but I agree. Thanks

2024-12-14 06:22 UTC, TickyWill commented on bmfuncts/use_otps.py
> +    author_to_check_list = lists_tup[2]
Pointed out by pylint too. Corrected. Thanks.

2024-12-14 06:23 UTC, TickyWill commented on bmfuncts/use_otps.py
> +            for auth_idx in dpt_auth_idx_list:
It is used now ! Thanks

2024-12-14 06:24 UTC, TickyWill commented on bmfuncts/use_otps.py
> +        wb, ws = _set_lab_otp_ws(lab_df, lab, dfs_tup, lab_otp_list, wb, first,
Done. thanks

2024-12-14 06:25 UTC, TickyWill commented on bmfuncts/useful_functs.py
> +#def mise_en_page(institute, org_tup, df,
Done. Thanks

2024-12-14 06:25 UTC, TickyWill commented on bmfuncts/use_otps.py
> +    cols_tup = otps_history_tup[1]
Corrected. Thanks

2024-12-14 07:37 UTC, TickyWill commented on bmfuncts/use_otps.py
> +def _set_saved_dept_otps(institute, org_tup, otps_history_tup,
Corrected. Thanks

2024-12-14 09:52 UTC, TickyWill commented on bmfuncts/add_ifs.py
> +def add_if(institute, org_tup, bibliometer_path, paths_tup, corpus_year):
Corrected. Thanks

2024-12-14 09:52 UTC, TickyWill commented on bmfuncts/format_files.py
> +from bmfuncts.rename_cols import set_col_attr
Pointed out by pylint too. Thanks

2024-12-14 13:39 UTC, TickyWill commented on bmfuncts/use_otps.py
> +    otp_col = cols_tup[5]
Corrected. Thanks

2024-12-14 13:40 UTC, TickyWill commented on bmfuncts/use_otps.py
> +def _set_lab_otp_ws(lab_df, lab, dfs_tup, lab_otp_list, wb, first, common_args_tup):
Corrected. Thanks

2024-12-14 13:40 UTC, TickyWill commented on bmfuncts/use_otps.py
> +def _re_save_labs_otp_file(institute, org_tup, dpt_pub_dict, dpt_lab_otps_dict,
Corrected. thanks

2024-12-14 13:54 UTC, TickyWill commented on bmfuncts/build_otps_info.py
> +        dpt = _try_init_dict(dept_otps_dict, dpt, dept)
Since it is an internal function, "dept" is known without pasing it as parameter. For seek of clarity, I've added it as arg of the internal function.

2024-12-14 13:54 UTC, TickyWill commented on bmfuncts/format_files.py
> +def build_data_val(values_list):
Docstring filled. Thanks

2024-12-14 14:41 UTC, TickyWill commented on bmfuncts/impact_factors_analysis.py
> +            db_dept_kpi_df = db_dept_kpi_df.merge(dept_kpi_df, how="outer",
OK. I'll keep this introduction of validate parameter for next release. Thanks

2024-12-14 14:44 UTC, TickyWill commented on bmfuncts/use_homonyms.py
> +    homonyms_history_df.drop(columns = [pub_id_col_alias], inplace = True)
So what is the use of inplace if not used in this case ? It allows shortening of lines when variable names are long to be clear. Open discussion.

2024-12-14 14:45 UTC, TickyWill commented on bmfuncts/use_homonyms.py
> +    homonyms_history_df = pd.merge(hash_id_df,
Kept for next release.

2024-12-16 08:40 UTC, BaptisteRefalo approved these changes

2024-12-16 13:52 UTC, merged