V6.0.0
TickyWill/BiblioMeter pull request #23
Opened 2024-12-16 14:51 UTC by TickyWill

The changes covers all the commits of the delated branch "new-enhance-add-OTP", nothing more. Thanks in advance for your review before merge into main.

2024-12-17 13:13 UTC, BaptisteRefalo commented
On the introduction page, section "Contributeurs et contacts", maybe you should add me, since I'm the one to contact in case of bugs and issues ;)

"Baptiste Refalo: Baptiste.REFALO@cea.fr"

2024-12-17 13:16 UTC, BaptisteRefalo commented
"Your code has been rated at 9.63/10 (previous run: 9.14/10, +0.49)": very good score, well done :)

2024-12-17 17:05 UTC, BaptisteRefalo requested changes
Review done :) -> a few things to enhance ("valide" parameter, no "inplace=true" for the "merge" method)

2024-12-17 17:07 UTC, BaptisteRefalo commented
You should add the following libraries in the requirements.txt file: openpyxl & pandas

2024-12-18 08:33 UTC, TickyWill commented on bmfuncts/add_ifs.py
> +                pass
Done

2024-12-18 08:41 UTC, TickyWill commented on bmfuncts/format_files.py
> +def format_wb_sheet(sheet_name, df, df_title, wb, first,
Docstring corrected

2024-12-18 08:47 UTC, TickyWill commented on bmfuncts/rename_cols.py
> +            continue
It doesn't seam clear from my point of view. I'll change it as :
```
if col in set_col_list:
    continue
else:
    final_col_attr_dict[col] = [15, "center"]
```

2024-12-18 08:48 UTC, TickyWill commented on bmfuncts/use_otps.py
> +                              inplace = True)
I prefer to use "inplace=True".

2024-12-18 08:48 UTC, TickyWill commented on bmfuncts/use_otps.py
> +    pub_id_otp_to_set_df.drop(columns=[hash_id_col_alias], inplace=True)
I prefer to use "inplace=True".

2024-12-18 08:52 UTC, TickyWill commented on bmfuncts/add_otps.py
> +    wb.save(xl_dpt_path)
Corrected. Thanks

2024-12-18 08:55 UTC, TickyWill commented on bmfuncts/impact_factors_analysis.py
> +            db_dept_kpi_df = db_dept_kpi_df.merge(dept_kpi_df, how="outer",
I'll keep the related changes for the next release because of deep tests that will be required. Thanks

2024-12-18 08:56 UTC, TickyWill commented on bmfuncts/use_otps.py
> +    hash_otps_history_df = pd.merge(hash_id_df,
I'll keep the related changes for the next release because of deep tests that will be required. Thanks

2024-12-18 08:58 UTC, TickyWill commented on bmfuncts/use_homonyms.py
> +    homonyms_history_df.drop(columns = [pub_id_col_alias], inplace = True)
I prefer to use "inplace=True". Thanks

2024-12-18 08:59 UTC, TickyWill commented on bmfuncts/use_homonyms.py
> +        mats_to_keep_df.drop(columns=[hash_id_col_alias], inplace=True)
I prefer to use "inplace=True". Thanks

2024-12-18 08:59 UTC, TickyWill commented on bmfuncts/use_homonyms.py
> +        mats_to_keep_df = pd.merge(hash_id_df,
I'll keep the related changes for the next release because of deep tests that will be required. Thanks

2024-12-18 09:00 UTC, TickyWill commented on bmfuncts/use_otps.py
> +        pass
Removed. Thanks

2024-12-18 09:01 UTC, TickyWill commented on bmfuncts/use_homonyms.py
> +    homonyms_history_df = pd.merge(hash_id_df,
I'll keep the related changes for the next release because of deep tests that will be required. Thanks

2024-12-19 06:55 UTC, merged

2024-12-19 06:58 UTC, TickyWill commented
Finally, I have suppressed the use of 'inplace=True' when modifying dataframes. Thanks.